#' @title Compute delta change
#'
#' @description Fetches data from in-memory / local sqlite database
#' @param db_object tables in a human exercise object generated by fetchdata
#' @param start starting interval for delta change
#' @param end ending interval for delta change
#' @param method ending interval for delta change
#' @import tidyverse
#' @import purrr
#' @import DBI
#' @import stringr
#' @import dplyr
#' @import tibble
#' @import tidyr
#' @export delta_change
#' @examples \dontrun{
#' hello()
#' }

delta_change = function(db_object,
                        start = 0,
                        end = 6,
                        method = 'none'){

  t0 = as.character(start)
  t = as.character(end)

  data = db_object@data %>%
    gather(variable, value, -Subject, -Gender, -Exercise, -interval) %>%
    spread(interval, value)


  if(method == 'none'){

    data %>%
      dplyr::mutate(
        delta = get(t) - get(t0),
        percent_change = (get(t) - get(t0))/get(t0) * 100
      )


  } else if(method == 'locf'){

    data %>%
      dplyr::mutate(
        `1` = ifelse(is.na(`1`), `0`, `1`),
        delta = get(t) - get(t0),
        percent_change = (get(t) - get(t0))/get(t0) * 100
      )

  } else if (method == 'averaged'){

    data %>%
      dplyr::mutate(
        baseline = rowMeans(.[c('0', '1')], na.rm = T),
        delta = get(t) - get('baseline'),
        percent_change = (get(t) - get('baseline'))/get('baseline') * 100
      )

  }


}
